add_newline = true

##########################

## iceburg + sakana

##########################

# [character]
# format = "[>](bold #84a0c6)[ε](bold #b4be82)[ε](bold #e2a478)[ε](bold #a093c7)[ ﾟ>](bold #89b8c2) "
# success_symbol = "[>](bold #89b8c2) "
# error_symbol = "🥺"

# [directory]
# truncation_length = 100
# truncate_to_repo = false
# style = "#84a0c6"
# home_symbol = "〜"

##########################

## menhera

##########################

[character]
format = "[> ](bold #dda0dd)"
style_success = "#ff69b4"
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[directory]
truncation_length = 100
truncate_to_repo = false
style = "#ba55d3"
home_symbol = "〜"

[nodejs]
style = "#ffc0cb"

[package]
style = "#ffc0cb"
symbol = " "

##########################

[memory_usage]
disabled = true

[git_branch]
style = "#dda0dd"
symbol = "♥:\uf113 "
truncation_length = 20
truncation_symbol = ""

[git_commit]
commit_hash_length = 30

[git_state]
progress_divider = " of "
cherry_pick = "🍒 PICKING"

[git_status]
conflicted = "🏳 "
ahead = "🏎 💨"
behind = "😰"
diverged = "😵"
untracked = "🤷<200d>"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑 "